title: Grapple 2.0 documentation
description: The documentation for the entire Grapple 2.0 project.
theme: just-the-docs

url: https://rhinox-training.github.io/grpl-2.0/

mermaid:
    version: "10.1.0"


logo: "assets/imgs/GrappleLogoWhite.png"