title: Grapple 2.0 documentation
description: The documentation for the entire Grapple 2.0 project.
theme: just-the-docs
baseUrl: grpl-2.0/docs
url: https://rhinox-training.github.io/grpl-2.0/

mermaid:
    version: "10.1.0"


logo: "docs/assets/imgs/GrappleLogoWhite.png"
favicon_ico: "docs/assets/imgs/GrappleLogoWhite.ico"
