title: Grapple 2.0 documentation
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://rhinox-training.github.io/grpl-2.0/

mermaid:
    version: "10.1.0"

